n1=input("enter number 1 :")
n2=input("enter number 2 :")
n3=input("enter number 3 :")
n4=input("enter number 4 :")
n5=input("enter number 5 :")
n1=int(n1)
n2=int(n2)
n3=int(n3)
n4=int(n4)
n5=int(n5)
result=n1+n2+n3+n4+n5
print("總和 :",result)
numbers=[n1,n2,n3,n4,n5]
numbermax=max(numbers)
print("最大數為 :",numbermax)