n1=input("enter a number")
n2=input("enter a number")
n3=input("enter a number")
n4=input("enter a number")
n5=input("enter a number")
n1=int(n1)
n2=int(n2)
n3=int(n3)
n4=int(n4)
n5=int(n5)
result=n1+n2+n3+n4+n5
print(result)